# Project information
site_name: MAGELLAN 7 Schulungsunterlagen (DA)
site_description: 'MAGELLAN 7 Schulungsunterlagen für Deutsche Auslandsschulen'
site_author: 'STÜBER SYSTEMS GmbH'
site_url: 'https://doc.magellan-schulungen.stueber-da.de'

# Copyright
copyright: © 2019 STÜBER SYSTEMS GmbH

# Repository
repo_name: 'Auf GitHub'
repo_url: 'https://github.com/stuebersystems/doc.magellan-schulungen-da.de'

# Theming
theme: 
    name: null
    custom_dir: 'theme'
    language: de
    direction:
    feature:
        tabs: false
    palette:
        primary: 'blue'
        accent: 'deep orange'
    font:
        text: Roboto
        code: Roboto Mono
    favicon: assets/logos/favicon.ico
    logo: 'assets/logos/logo.svg'
    include_search_page: false
    search_index_only: true
    static_templates:
      - 404.html

# Customization
extra_css:
    - assets/css/custom.css
    
# Extensions    
markdown_extensions:
    - admonition

# Plugins    
plugins:
    - search
    - img2fig
  
# Navigation  
nav:
- Überblick: index.md
- M01 - MAGELLAN Einführung: m01_magellan_einfuehrungsschulung.md
- M02 - MAGELLAN Zeugniskarte und Oberstufe:
  - Einführung: m02_magellan_zeugniskarte.md  
  - Einstellungen und Schlüsselverzeichnisse: einstellungen-und-schlusselverzeichnisse.md
  - Zeugniskarte: zeugniskarte.md
  - Fachwahlkarte: m02.fachwahl.md
  - Oberstufe DAS: m02.abitur.md
- M03 - MAGELLAN Administrator: m03_magellan_administrator.md
